//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.1.3")]
[assembly: AssemblyFileVersion("0.1.3.0")]
[assembly: AssemblyCopyright("Copyright © --Company Name Here-- 2011")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("--Company Name Here--")]
[assembly: AssemblyProduct("Machine.Specifications.AutoMocking (Debug DB: 0)")]


