//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.4.24")]
[assembly: AssemblyFileVersion("1.4.24.0")]
[assembly: AssemblyCopyright("Copyright (c) James Broome 2011")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("James Broome")]
[assembly: AssemblyProduct("Machine.Specifications.AutoMocking attempts to reduce noise in MSpec tests when c" +
    "reating mock objects, dependencies and the subject under test. (Debug DB: 0)")]


